websocket {
	port: 8223
	no_tls: true
}

jetstream {
  max_mem_store: 2Gb
  max_file_store: 10Gb
}

accounts {
    API: {
		jetstream: enabled
		users: [
			{ user: admin, password: admin }
		]
    }
	SYS: {}
}

system_account: SYS

authorization {
 	auth_callout: {
		issuer: ADQ553YNU2F65Y3FW75AAOGN5DCKSBCKESXBFCQJYZWQUDQDN2DWE6OT
		auth_users: [ admin ]
		account: API
	}
}
